  name: "Generate Markdown TOC"
  description: "Adds or updates a Table of Contents in README.md files"
  inputs:
    target-dir:
      description: "Path to the directory to scan for README files"
      required: false
      default: "."
  runs:
    using: "composite"
    steps:
      - shell: bash
        run: |
          set -e
          chmod +x "${{ github.action_path }}/src/generate-toc.sh"
          "${{ github.action_path }}/src/generate-toc.sh" "${{ inputs.target-dir }}"
