# action.yml – lives at repo root
name: "Generate Markdown TOC"
description: "Adds or updates a Table of Contents in README.md"
inputs:
  target-file:
    description: "Path to the Markdown file"
    required: false
    default: README.md
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -euo pipefail
        chmod +x "${{ github.action_path }}/src/generate-toc.sh"

        echo "🔍  Locating README files..."
        mapfile -d '' files < <(
          find "${{ github.workspace }}" -type f -iname 'README*.md' -print0
        )

        for f in "${files[@]}"; do
          echo "⚙️  Generating TOC for $f"
          "${{ github.action_path }}/src/generate-toc.sh" "$f" | sponge "$f"
        done
